name: Set up Python
description: Install Python with appropriate defaults for NI Python projects.
inputs:
  python-version:
    default: 3.11.9
outputs:
  python-path:
    value: ${{ steps.setup-python.outputs.python-path }}
  python-version:
    value: ${{ steps.setup-python.outputs.python-version }}
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      id: setup-python
      with:
        python-version: ${{ inputs.python-version }}
    - name: Add pythonVersion environment variable
      run: | # zizmor: ignore[github-env] # value is queried from the installed Python interpreter, not user input
        echo "pythonVersion=$PYTHON_VERSION" >> "$GITHUB_ENV"
      shell: bash
      env:
        PYTHON_VERSION: ${{ steps.setup-python.outputs.python-version }}
