name: Test actions

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test_setup_python:
    name: Test setup-python
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: [3.9, '3.10', 3.11, 3.12, 3.13]
    steps:
      - name: Check out repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Python
        uses: ./setup-python
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check Python version
        run: |
          import sys
          version = sys.version_info[:2]
          expected_version = tuple("${{ matrix.python-version }}".split("."))
          if version != expected_version:
              print(f"::error title=Test Failure::The Python version does not match. Got {version}, expected {expected_version}.")
              sys.exit(1)
        shell: python
  test_setup_poetry:
    name: Test setup-poetry
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: [3.9, '3.10', 3.11, 3.12, 3.13]
    steps:
      - name: Check out repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Python
        uses: ./setup-python
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Poetry
        uses: ./setup-poetry
      - name: Create project
        run: poetry new test-project
      - name: Check that the project was created
        run: |
          if [ ! -f test-project/pyproject.toml ]; then
            echo "::error title=Test Failure::The project file does not exist."
            exit 1
          fi
        shell: bash
  test_check_project_version:
    name: Test check-project-version
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Python
        uses: ./setup-python
      - name: Set up Poetry
        uses: ./setup-poetry
      - name: Create project with version 1.0.0
        run: |
          poetry new test-project
          poetry version 1.0.0 -C test-project
      - name: Check version == 1.0.0
        uses: ./check-project-version
        with:
          project-directory: test-project
          expected-version: 1.0.0
      - name: Create a notice about the expected failure
        run: echo "::notice title=Notice::The next step is expected to fail."
      - name: Check version == 1.0.1 (expected to fail)
        id: expected-failure
        continue-on-error: true
        uses: ./check-project-version
        with:
          project-directory: test-project
          expected-version: 1.0.1
      - name: Error if the previous step didn't fail
        if: steps.expected-failure.outcome != 'failure'
        run: |
          echo "::error title=Test Failure::The previous step did not fail as expected."
          exit 1
  test_update_project_version:
    name: Test update-project-version
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Python
        uses: ./setup-python
      - name: Set up Poetry
        uses: ./setup-poetry
      - name: Create project with version 1.0.0
        run: |
          poetry new test-project
          poetry version 1.0.0 -C test-project
      - name: Update version to 1.0.1
        uses: ./update-project-version
        with:
          project-directory: test-project
          create-pull-request: false
          version-rule: patch
          use-dev-suffix: false
      - name: Check version == 1.0.1
        uses: ./check-project-version
        with:
          project-directory: test-project
          expected-version: 1.0.1
      - name: Update version to 1.0.2.dev0
        uses: ./update-project-version
        with:
          project-directory: test-project
          create-pull-request: false
      - name: Check version == 1.0.2.dev0
        uses: ./check-project-version
        with:
          project-directory: test-project
          expected-version: 1.0.2.dev0
      - name: Update version to 1.0.2.dev1
        uses: ./update-project-version
        with:
          project-directory: test-project
          create-pull-request: false
      - name: Check version == 1.0.2.dev1
        uses: ./check-project-version
        with:
          project-directory: test-project
          expected-version: 1.0.2.dev1
